document.writeln("<!doctype html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, user-scalable=no\'>");
document.writeln("<title>Courses</title>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/bootstrap.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/font-awesome.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/edua-icons.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/animate.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/owl.carousel.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/owl.transitions.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/cubeportfolio.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/settings.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/bootsnav.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/style.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/loader.css\'>");
document.writeln("");
document.writeln("<link rel=\'icon\' href=\'images/favicon.png\'>");
document.writeln("");
document.writeln("<!--[if lt IE 9]>");
document.writeln("  <script src=\'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\'></script>");
document.writeln("  <script src=\'https://oss.maxcdn.com/respond/1.4.2/respond.min.js\'></script>");
document.writeln("<![endif]-->");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--FOOTER-->");
document.writeln("<footer class=\'padding-top\'>");
document.writeln("  <div class=\'container\'>");
document.writeln("    <div class=\'row\'>");
document.writeln("      <div class=\'col-md-4 col-sm-4 footer_panel bottom25\'>");
document.writeln("        <h3 class=\'heading bottom25\'>About Us<span class=\'divider-left\'></span></h3>");
document.writeln("        <a href=\'index.html\' class=\'footer_logo bottom25\'><img src=\'images/logo-white.png\' alt=\'Edua\'></a>");
document.writeln("        <p>We offer the most complete house renovating services in the country, from kitchen design to bathroom remodeling.</p>");
document.writeln("        <ul class=\'social_icon top25\'>");
document.writeln("          <li><a href=\'#.\' class=\'facebook\'><i class=\'fa fa-facebook\'></i></a></li>");
document.writeln("          <li><a href=\'#.\' class=\'twitter\'><i class=\'icon-twitter4\'></i></a></li>");
document.writeln("          <li><a href=\'#.\' class=\'dribble\'><i class=\'icon-dribbble5\'></i></a></li>");
document.writeln("          <li><a href=\'#.\' class=\'instagram\'><i class=\'icon-instagram\'></i></a></li>");
document.writeln("          <li><a href=\'#.\' class=\'vimo\'><i class=\'icon-vimeo4\'></i></a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\'col-md-4 col-sm-4 footer_panel bottom25\'>");
document.writeln("        <h3 class=\'heading bottom25\'>Quick Links<span class=\'divider-left\'></span></h3>");
document.writeln("        <ul class=\'links\'>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Home</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Company</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Services</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Our Team</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Company History</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Certifications</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Blog</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Shop</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Privacy Policy</a></li>");
document.writeln("          <li><a href=\'#.\'><i class=\'icon-chevron-small-right\'></i>Contact Us</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\'col-md-4 col-sm-4 footer_panel bottom25\'>");
document.writeln("        <h3 class=\'heading bottom25\'>Keep in Touch <span class=\'divider-left\'></span></h3>");
document.writeln("        <p class=\' address\'><i class=\'icon-map-pin\'></i>198 West 21th Street Victoria 8007, Australia</p>");
document.writeln("        <p class=\' address\'><i class=\'icon-phone\'></i>(654) 332-112-222</p>");
document.writeln("        <p class=\' address\'><i class=\'icon-mail\'></i><a href=\'mailto:Edua@info.com\'>Edua@info.com</a></p>");
document.writeln("        <img src=\'images/footer-map.png\' alt=\'we are here\' class=\'img-responsive\'>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</footer>");
document.writeln("");
document.writeln("<!--FOOTER ends-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script src=\'js/jquery-2.2.3.js\'></script>");
document.writeln("<script src=\'js/bootstrap.min.js\'></script>");
document.writeln("<script src=\'js/bootsnav.js\'></script>");
document.writeln("<script src=\'js/jquery.appear.js\'></script>");
document.writeln("<script src=\'js/jquery-countTo.js\'></script>");
document.writeln("<script src=\'js/jquery.parallax-1.1.3.js\'></script>");
document.writeln("<script src=\'js/owl.carousel.min.js\'></script>");
document.writeln("<script src=\'js/jquery.cubeportfolio.min.js\'></script>");
document.writeln("<script src=\'js/jquery.themepunch.tools.min.js\'></script>");
document.writeln("<script src=\'js/jquery.themepunch.revolution.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.layeranimation.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.navigation.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.parallax.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.slideanims.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.video.min.js\'></script>");
document.writeln("<script src=\'js/wow.min.js\'></script>");
document.writeln("<script src=\'js/functions.js\'></script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
