document.writeln("<!doctype html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1, user-scalable=no\'>");
document.writeln("<title>Courses</title>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/bootstrap.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/font-awesome.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/edua-icons.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/animate.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/owl.carousel.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/owl.transitions.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/cubeportfolio.min.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/settings.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/bootsnav.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/style.css\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/loader.css\'>");
document.writeln("");
document.writeln("<link rel=\'icon\' href=\'images/favicon.png\'>");
document.writeln("");
document.writeln("<!--[if lt IE 9]>");
document.writeln("  <script src=\'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\'></script>");
document.writeln("  <script src=\'https://oss.maxcdn.com/respond/1.4.2/respond.min.js\'></script>");
document.writeln("<![endif]-->");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<!--Header-->");
document.writeln("<header>");
document.writeln("    <nav class=\'navbar navbar-default navbar-fixed white no-background bootsnav\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'search_btn btn_common\'><i class=\'icon-icons185\'></i></div>");
document.writeln("            <div class=\'navbar-header\'>");
document.writeln("                <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'#navbar-menu\'>");
document.writeln("                    <i class=\'fa fa-bars\'></i>");
document.writeln("                </button>");
document.writeln("                <a class=\'navbar-brand\' href=\'index.html\'><img src=\'images/logo-white.png\' alt=\'logo\' class=\'logo logo-display\'>");
document.writeln("                    <img src=\'images/logo.png\' class=\'logo logo-scrolled\' alt=\'\'>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbar-menu\'>");
document.writeln("                <ul class=\'nav navbar-nav navbar-right\' data-in=\'fadeInDown\' data-out=\'fadeOut\'>");
document.writeln("                    <li><a href=\'home.jsp\'>首页</a></li>");
document.writeln("                    <li><a href=\'college.jsp\'>学院</a></li>");
document.writeln("                    <li><a href=\'Teacher.jsp\'>教师</a></li>");
document.writeln("                    <li><a href=\'my_message.jsp\'>我的留言</a></li>");
document.writeln("                    <li><a href=\'add_message.jsp\'>添加留言</a></li>");
document.writeln("                    <li><a href=\'#\'>欢迎${cur_user.sid}</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("</header>");
document.writeln("");
document.writeln("");
document.writeln("<!--Search-->");
document.writeln("<div id=\'search\'>");
document.writeln("    <button type=\'button\' class=\'close\'>×</button>");
document.writeln("    <form>");
document.writeln("        <input type=\'search\' value=\'\' placeholder=\'Search here....\'  required/>");
document.writeln("        <button type=\'submit\' class=\'btn btn_common blue\'>Search</button>");
document.writeln("    </form>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script src=\'js/jquery-2.2.3.js\'></script>");
document.writeln("<script src=\'js/bootstrap.min.js\'></script>");
document.writeln("<script src=\'js/bootsnav.js\'></script>");
document.writeln("<script src=\'js/jquery.appear.js\'></script>");
document.writeln("<script src=\'js/jquery-countTo.js\'></script>");
document.writeln("<script src=\'js/jquery.parallax-1.1.3.js\'></script>");
document.writeln("<script src=\'js/owl.carousel.min.js\'></script>");
document.writeln("<script src=\'js/jquery.cubeportfolio.min.js\'></script>");
document.writeln("<script src=\'js/jquery.themepunch.tools.min.js\'></script>");
document.writeln("<script src=\'js/jquery.themepunch.revolution.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.layeranimation.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.navigation.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.parallax.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.slideanims.min.js\'></script>");
document.writeln("<script src=\'js/revolution.extension.video.min.js\'></script>");
document.writeln("<script src=\'js/wow.min.js\'></script>");
document.writeln("<script src=\'js/functions.js\'></script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
